# Generated by Django 2.1.2 on 2018-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=70)),
                ('raza', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
