# Generated by Django 2.1.2 on 2018-11-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
    ]
